FROM registry.access.redhat.com/ubi8/nodejs-18:latest AS builder

WORKDIR /app
RUN chown -R 1001:0 /app && chmod -R g+rwX /app
USER 1001

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build
RUN npm prune --omit=dev

FROM registry.access.redhat.com/ubi8/nodejs-18-minimal:latest

WORKDIR /app
RUN chown -R 1001:0 /app && chmod -R g+rwX /app

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=1337

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/config ./config
COPY --from=builder /app/public ./public

USER 1001

EXPOSE 1337

CMD ["node", "node_modules/.bin/strapi", "start"]
