FROM icr.io/appcafe/websphere-liberty:kernel-java25-openj9-ubi-minimal

ARG VERBOSE=false
ARG LICENSE=accept

COPY --chown=1001:0 server.xml /config/
COPY --chown=1001:0 jvm.options /config/

RUN features.sh

COPY --chown=1001:0 app.jar /config/apps/app.jar

RUN configure.sh